<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title>Libris</title>
</head>
<body>
<header>
    <h1>Libris back office</h1>
    <menu>
        <li><a href="index.php?route=home">Home</a></li>
    </menu>
    <?php if (isset($isAdmin)) {
        if($isAdmin === true) {?>
            <menu>
                <li><a href="index.php?route=admin-books-list">Books List</a></li>
                <li><a href="index.php?route=admin-users-list">Users List</a></li>
                <li><a href="index.php?route=admin-comments-list">Comments List</a></li>
            </menu>
        <?php }
    }?>
</header>
<?php
require  "templates/$template.phtml";
?>
</body>