
<?php if (isset($errors)) {
    foreach($errors as $error) { ?>
        <p><?= $error ?></p>
        <?php
    }
}?>
        <section>
            <?php if(isset($book)) { ?>
                <div class="container-book-cover">
                    <div id="cover-id"><?= $book->getCoverId()?></div>
                </div>
            <div class="container-book-info">
                <h1><?= $book->getTitle()?></h1>
                <p><?= $book->getAuthor()?></p>
                <p><?= $book->getPublishYear()?></p>
            </div>
                <button type="submit">Add to list</button>
            <?php } else {?>
            <p>Book Unfound</p>
            <?php }?>
        </section>

<script type="application/javascript" src="src/api/detail_book_script.js"></script>
