
<?php if (isset($errors)) {
    foreach($errors as $error) { ?>
        <p><?= $error ?></p>
        <?php
    }
}?>
        <section class="container-book-detail">
            <?php if(isset($book)) { ?>
                <div class="div-book-cover">
                    <!--Ne pas oublier de cacher la div avec l'id du livre -->
                    <div id="cover-id"><?= $book->getCoverId()?></div>
                </div>
            <div class="div-info-add">
                <div class="div-book-info">
                    <h2 class="detail-book-title"><?= $book->getTitle()?></h2>
                    <p class="detail-book-author"><?= $book->getAuthor()?></p>
                    <p class="detail-book-year"><?= $book->getPublishYear()?></p>
                </div>
                <div class="div-add-button">
                    <button class="button-add-to-list" type="submit">Add to list</button>
                </div>
            </div>

            <?php } else {?>
            <p>Book Unfound</p>
            <?php }?>
        </section>

<script type="application/javascript" src="src/api/detail_book_script.js"></script>
