<main class="booklist">
<div class="list-div"></div>
    <?php
    if ($_SESSION['user_id']) {
        if(isset($booksList)) {
        foreach ($booksList as $book) { ?>
            <div class="book-list-div">
                <ul>
                    <li class="list-book-title"><?=$book->getTitle()?></li>
                    <li class="list-book-author"><?= $book->getAuthor()?></li>
                </ul>
            </div>
        <?php }
        }
    }?>


</main>