
<?php if (isset($errors)) {
    foreach($errors as $error) { ?>
        <p><?= $error ?></p>
        <?php
    }
}?>
        <section class="container-book-detail">
            <?php if(isset($book)) { ?>
                <div class="div-book-cover">
                    <!--Ne pas oublier de cacher la div avec l'id du livre -->
                    <div id="cover-id"><?= $book->getCoverId()?></div>
                </div>
            <div class="div-info-add">
                <div class="div-book-info">
                    <h2 class="detail-book-title"><?= $book->getTitle()?></h2>
                    <p class="detail-book-author"><?= $book->getAuthor()?></p>
                    <p class="detail-book-year"><?= $book->getPublishYear()?></p>
                </div>
                <div class="div-add-button">
                    <button class="button-add-to-list" type="submit">Add to list</button>
                </div>
            </div>
                <div class="div-add-comment">
                <form method="post" action="index.php?route=add-comment&id=<?= $book->getBookId() ?>">
                    <fieldset class="fieldset-comment-content-title">
                        <label  for="comment-title" class="label-comment-title label-comment">Title</label>
                        <input type="text" name="comment-title" id="comment-title" placeholder="Your title here" maxlength="40" required>
                        <label for="comment-content" class="label-comment-content label-comment">Content</label>
                        <input type="text" name="comment-content" id="comment-content" placeholder="Your comment here" minlength="30" maxlength="750" required">
                    </fieldset>
                    <fieldset class="fieldset-comment-submit">
                        <button type="submit">Submit comment</button>
                    </fieldset>
                </form>
                </div>
            <?php } else {?>
                <p>Book Unfound</p>
            <?php }?>
        </section>

            <?php //if (isset($_SESSION['user-id'])) { ?>

            <?php// } ?>



<script type="application/javascript" src="src/api/detail_book_script.js"></script>
