


<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <link href="./assets/css/style.css" rel="stylesheet" />
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css"
    />
    <title>Libris</title>
</head>
<body>
<header class="header">
    <div class="header-container">
        <div class="header-top">
            <img class="logo-libris" alt="Logo de libris" src="./assets/img/logo.png"/>
            <h1>Libris</h1>
            <div class="header-top-right">
                <img class="switch-dark-mode" alt="switch dark mode" src="./assets/img/switch-dark-mode.png"/>>
                <div id="root">
                    <div id="topnav" class="topnav">
                        <a id="topnav-hamburger-icon" href="javascript:void(0);" onclick="showResponsiveMenu()">
                            <span></span>
                            <span></span>
                            <span></span>
                        </a>
                        <div class="container-menu-burger">
                            <nav role="navigation" id="topnav-menu-burger">
                                <ul>
                                    <?php if(isset($sessionUserId)) { ?>
                                        <li>
                                            <a href="index.php?route=profile&id=<?php { echo $sessionUserId; } ?>">Profile</a>
                                        </li>
                                    <?php } ?>
                                    <li><a href="index.php?route=login" class="login-logout">Login</a></li>
                                    <li><a href="index.php?route=logout" class="login-logout">Logout</a></li>
                                    <li><a href="index.php?route=create-user">Register</a></li>
                                    <li><a href="index.php?route=users-list">Users list</a></li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-bottom">
           <a href="index.php?route=home">Home</a>
        </div>
        <?php if (isset($isAdmin)) {
                    if($isAdmin === true) {?>
                        <a href="index.php?route=admin-home">Back Office</a>
                    <?php }
        } ?>
    </div>
</header>
<?php
require  "templates/$template.phtml";
?>

<script type="application/javascript" src="src/api/test-function.js"></script>
<script type="application/javascript" src="assets/js/menu-burger.js"></script>
<script src="/libris/assets/js/swiper.js"></script>
</body>
</html>