


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="Libris est un site communautaire de découverte et partage autour de la littérature. Ici, vous pouvez chercher de nouvelle lecture grâce à notre moteur de recherche, ajouter des livres à vos favoris et partager vos impressions avec la communauté." />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="./assets/css/style.css" rel="stylesheet" />
    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/swiper@12/swiper-bundle.min.css"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


    <title>Libris</title>
</head>
<body>
<header class="header">
    <div class="header-container">
        <div class="header-top">
            <img class="logo-libris" alt="Logo de libris" src="./assets/img/logo.png"/>
            <h1>Libris</h1>
            <div class="header-top-right">
            </div>
        </div>
        <div class="header-bottom">
           <a href="index.php?route=home">Home</a>
            <nav class="nav-menu">
                <ul>
                    <?php if(isset($sessionUserId)) { ?>
                        <li>
                            <a href="index.php?route=profile&id=<?php { echo $sessionUserId; } ?>">Profile</a>
                        </li>
                    <?php } ?>
                    <li><a href="index.php?route=login" class="login-logout">Login</a></li>
                    <li><a href="index.php?route=logout" class="login-logout">Logout</a></li>
                    <li><a href="index.php?route=create-user">Register</a></li>
                    <li><a href="index.php?route=users-list">Users list</a></li>
                </ul>
            </nav>
        </div>
        <?php if (isset($isAdmin)) {
                    if($isAdmin === true) {?>
                        <a href="index.php?route=admin-home">Back Office</a>
                    <?php }
        } ?>
    </div>
</header>
<?php
require  "templates/$template.phtml";
?>
<script type="module" src="./assets/js/main.js"></script>
<script type="module">
    import Swiper from 'https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.mjs';
    import Navigation from 'https://cdn.jsdelivr.net/npm/swiper@11/modules/navigation.min.mjs';
    import Pagination from 'https://cdn.jsdelivr.net/npm/swiper@11/modules/pagination.min.mjs';

    const swiper = new Swiper('.swiper', {
        modules: [ Navigation, Pagination ],
        slidesPerView: 5,
        spaceBetween: 30,
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev"
        },
        scrollbar: {
            el: ".swiper-scrollbar",
            draggable: true
        }
    });
</script>
<footer>
    <div class="footer-content">
        <p class="mentions-legales">2026 Libris | CGU | Politique de confidentialité</p>
        <p class="p-follow">Nous suivre sur les réseaux</p>
        <div class="social-medias">
            <span><i class="fa-brands fa-square-facebook" style="color: #f6e06e;"></i></i></span>
            <span><i class="fa-brands fa-square-instagram" style="color: #f6e06e;"></i></span>
            <span><i class="fa-brands fa-linkedin" style="color: #f6e06e;"></i></span>
        </div>
    </div>
</footer>
</body>

</html>