<form class="form-login form" method="post" action="index.php?route=check-login">
    <?php if(isset($errors)) {
        foreach ($errors as $error) {
            ?> <p><?= $error ?></p>
        <?php }
    }?>
    <label>Email</label>
    <input type="email" class="form-input" name="email-login" id="email-login" required>
    <label>Password</label>
    <input type="password" class="form-input" name="password-login" id="password-login" required>
    <button type="submit">Submit</button>
</form>