<form class="form registration-form" method="POST" action="index.php?route=check-create-user">
    <fieldset class="fielset input-fieldset">
        <label class="label">Username</label>
        <input type="text" name="username" id="username" class="form-input" required>
        <label class="label">Email</label>
        <input type="email" name="email" id="email" class="form-input" required>
        <label class="label">Password</label>
        <input type="password" name="password" id="password" class="form-input" required>
        <label class="label">Intro</label>
        <input type="text" name="intro" id="intro" class="form-input" required>
    </fieldset>
    <fieldset class="fieldset submit-fieldset">
        <button type="submit">Submit</button>
    </fieldset>
</form>