<h2>Update profile</h2>
<form method="post" action="index.php?route=check-update-user&id=<?= $user->getId() ?>">
    <?php if(isset($errors)) {
        foreach ($errors as $error) {
            ?> <p><?= $error ?></p>
        <?php }
    }?>
    <fieldset class="fieldset input-fieldset">
        <label class="label">Username</label>
        <!-- Vérifier la value et décider si on peut changer le nom d'utilisateur ou non (readonly)-->
        <input type="text" name="username" value="<?php echo $user->getUsername(); ?>" required/>
        <label class="label">Password</label>
        <input type="password" name="password" required />
        <label class="label">Confirm password</label>
        <input type="password" name="confirm-password" required />
        <label class="label">Email</label>
        <!-- Vérifier la value -->
        <input type="email" name="email" value="<?php echo $user->getEmail(); ?>" required readonly/>
        <label class="label">Intro</label>
        <input type="text" name="intro" value="<?php echo $user->getIntro(); ?>" required />
    </fieldset>
    <fieldset class="fieldset button-fieldset">
        <button class="button">Submit</button>
    </fieldset>
</form>
