<main>
<?php if (isset($errors)) {
    foreach($errors as $error) { ?>
        <p><?= $error ?></p>
        <?php
    }
}?>
    <h2>Register</h2>
    <form class="form form-register" method="POST" action="index.php?route=check-create-user">
            <input type="hidden" name="csrf_token" id="csrf_token" value="<?= $_SESSION["csrf_token"] ?>" />
            <label class="label">Username</label>
            <input type="text" name="username" id="username" class="form-input" required>
            <label class="label">Email</label>
            <input type="email" name="email" id="email" class="form-input" required>
            <label class="label">Password</label>
            <input type="password" name="password" id="password" class="form-input" required>
            <label class="label">Confirm password</label>
            <input type="password" name="confirm-password" id="confirm-password" class="form-input" required>
            <label class="label">Intro</label>
            <input type="text" name="intro" id="intro" class="form-input" required>
            <button type="submit">Submit</button>
    </form>
</main>