

<main>
        <div class="div-profile">
            <?php if (isset($errors)) {
                foreach($errors as $error) { ?>
                    <p><?= $error ?></p>
                    <?php
                }
            }?>
            <?php if(isset($user)) { ?>
                <p><?php echo $user->getUsername() ?></p>
                <p>Last login : <?= $user->getLastLogin()->format('Y-m-d H:i') ?></p>
                <p><?=$user->getIntro()?></p>
            <?php if(isset($_SESSION['user_id'])) {
                if($user->getId() === $_SESSION['user_id']) { ?>
                    <button class="button-update-profile"><a href="index.php?route=update-user&amp;id=<?= $_SESSION["user_id"] ?>">Account settings</a></button>
               <?php }
                } ?>
            <section class="section-user-comments">
                <?php if(isset($comments)) {
                    foreach($comments as $comment) { ?>
                    <div class="card-user-comments">
                        <h3><?= $comment->getTitle()?></h3>
                        <p><a href="index.php?route=detail-book&amp;id=<?= $comment->getBookId()?>"><?= $comment->getBook()->getTitle()?></a></p>
                        <p><?= $comment->getContent()?></p>
                        <?php if($user->getId() === $_SESSION['user_id']) { ?>
                            <div class="div-remove-update-comment">
                                <form method="post" action="index.php?route=delete-comment&amp;id=<?= $comment->getCommentId() ?>">
                                    <button type="submit" class="button-delete-comment">Delete</button>
                                </form>
                            </div>
                            <?php }?>
                    </div>
                 <?php }
                    } ?>
            </section>
            <div class="list-div"></div>
            <?php
                if(isset($booksList)) {
                    foreach ($booksList as $book) { ?>
                        <div class="book-list-div">
                            <ul>
                                <li class="list-book-title"><?=$book->getTitle()?></li>
                                <li class="list-book-author"><?= $book->getAuthor()?></li>
                            </ul>
                            <?php if($_SESSION['user_id'] === $user->getId()) { ?>
                                    <p>Bouton ici</p>
                                <form method="post" action="index.php?route=remove-book-from-list&amp;id=<?= $book->getBookId() ?>">
                                <button type="submit" class="button-remove-book">Remove</button>
                            </form>
                            <?php } ?>
                        </div>
                    <?php }
                }?>
            <?php } ?>

        </div>
</main>
