

<main>
        <div class="div-profile">
            <?php if (isset($errors)) {
                foreach($errors as $error) { ?>
                    <p><?= $error ?></p>
                    <?php
                }
            }?>
            <section class="user-info">
                <?php if(isset($user)) { ?>
                    <h2>Welcome to <?php echo $user->getUsername() ?>'s profile</h2>
                    <p class="last-login">Last login : <?= $user->getLastLogin()->format('Y-m-d H:i') ?></p>
                    <p class="intro"><?=$user->getIntro()?></p>
                <?php if(isset($_SESSION['user_id'])) {
                    if($user->getId() === $_SESSION['user_id']) { ?>
                        <button class="button-update-profile"><a href="index.php?route=update-user&amp;id=<?= $_SESSION["user_id"] ?>">Account settings</a></button>
                   <?php }
                    } ?>
            </section>
            <section class="section-book-list">
                <div class="swiper">
                    <div class="swiper-wrapper">
                        <?php
                        if(isset($booksList)) {
                            foreach ($booksList as $book) { ?>
                                <div class="book-list-card swiper-slide">
                                    <?php if ($book->getCoverId()) { ?>
                                        <div class="div-book-cover">
                                            <div class="cover-id" hidden><?= $book->getCoverId()?></div>
                                        </div>
                                    <?php } ?>
                                    <h3 class="list-book-title"><?php
                                        if(strlen($book->getTitle()) > 20) {
                                            echo substr($book->getTitle(), 0, 20) . "...";
                                        } else {
                                            echo $book->getTitle();
                                        }
                                        ?></h3>
                                    <p class="list-book-author"><?php if(strlen($book->getAuthor()) > 20) {
                                            echo substr($book->getAuthor(), 0, 25) . "...";
                                        } else {
                                            echo $book->getAuthor();
                                        }?></p>
                                    <?php if($_SESSION['user_id'] === $user->getId()) { ?>
                                        <form method="post" action="index.php?route=remove-book-from-list&amp;id=<?= $book->getBookId() ?>">
                                            <button type="submit" class="button-remove-book">Remove</button>
                                        </form>
                                    <?php } ?>
                                </div>
                            <?php }
                        }
                        }?>
                    </div>
                    <div class="swiper-pagination"></div>
                    <div class="swiper-button-prev"></div>
                    <div class="swiper-button-next"></div>
                    <div class="swiper-scrollbar"></div>
                </div>
            </section>
            <section class="section-user-comments">
                <?php if(isset($comments)) {
                    foreach($comments as $comment) { ?>
                    <div class="card-user-comments">
                        <h3><?= $comment->getTitle()?></h3>
                        <p><a href="index.php?route=detail-book&amp;id=<?= $comment->getBookId()?>"><?= $comment->getBook()->getTitle()?></a></p>
                        <p><?= $comment->getContent()?></p>
                        <?php if($user->getId() === $_SESSION['user_id']) { ?>
                            <div class="div-remove-update-comment">
                                <form method="post" action="index.php?route=delete-comment&amp;id=<?= $comment->getCommentId() ?>">
                                    <button type="submit" class="button-delete-comment">Delete</button>
                                </form>
                            </div>
                            <?php }?>
                    </div>
                 <?php }
                    } ?>
            </section>
        </div>
</main>

